### ISSUE TITLE
Fehlschlagen von `ng test` im frontend

### ISSUE THREAD

**Issue by benedictweis** [SE-TINF22B2/G5-DuoGradus#165]
Hi, ich versuche gerade die frontend Github Action wieder zum laufen zu bekommen. Deshalb habe ich bei mir lokal mal `npm run test` ausgeführt. Dabei ergab sich der unten aufgeführte Fehler. Habe ich bei der Ausführung etwas falsch gemacht oder ist das aktuell so gedacht? In beiden fällen sollten wir das Problem beheben bevor ich die frontend Action wieder zum laufen bringe. Vielleicht könnt ihr @wwwLuis @Jstn2004 mir weiterhelfen?

```bash
> frontend@0.0.0 test
> ng test

✔ Browser application bundle generation complete.
09 05 2024 10:45:07.418:WARN [karma]: No captured browser, open http://localhost:9876/
09 05 2024 10:45:07.571:INFO [karma-server]: Karma v6.4.3 server started at http://localhost:9876/
09 05 2024 10:45:07.571:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
⠋ Generating browser application bundles...09 05 2024 10:45:07.610:INFO [launcher]: Starting browser ChromeHeadless
✔ Browser application bundle generation complete.
09 05 2024 10:45:14.021:INFO [Chrome Headless 124.0.6367.119 (Mac OS 10.15.7)]: Connected on socket 9Kqo7QXal5ib9wOTAAAB with id 40040901
Chrome Headless 124.0.6367.119 (Mac OS 10.15.7) SignupformComponent should create FAILED
        Error: NG0304: 'app-inputfield' is not a known element (used in the 'SignupformComponent' component template):
        1. If 'app-inputfield' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
        2. If 'app-inputfield' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        error properties: Object({ code: 304 })
            at validateElementIsKnown (node_modules/@angular/core/fesm2022/core.mjs:9662:23)
            at ɵɵelementStart (node_modules/@angular/core/fesm2022/core.mjs:22997:9)
            at ɵɵelement (node_modules/@angular/core/fesm2022/core.mjs:23072:5)
            at templateFn (ng:///SignupformComponent.js:14:9)
            at executeTemplate (node_modules/@angular/core/fesm2022/core.mjs:11268:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12470:13)
            at renderComponent (node_modules/@angular/core/fesm2022/core.mjs:12416:5)
            at renderChildComponents (node_modules/@angular/core/fesm2022/core.mjs:12518:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12498:13)
            at ComponentFactory.create (node_modules/@angular/core/fesm2022/core.mjs:15859:17)
Chrome Headless 124.0.6367.119 (Mac OS 10.15.7) ChallengeDialogComponent should create FAILED
        Error: NG05105: Unexpected synthetic property @openClose found. Please make sure that:
          - Either `BrowserAnimationsModule` or `NoopAnimationsModule` are imported in your application.
          - There is corresponding configuration for the animation named `@openClose` defined in the `animations` field of the `@Component` decorator (see https://angular.io/api/core/Component#animations).
        error properties: Object({ code: 5105 })
            at checkNoSyntheticProp (node_modules/@angular/platform-browser/fesm2022/platform-browser.mjs:690:15)
            at EmulatedEncapsulationDomRenderer2.setProperty (node_modules/@angular/platform-browser/fesm2022/platform-browser.mjs:644:13)
            at elementPropertyInternal (node_modules/@angular/core/fesm2022/core.mjs:11711:18)
            at ɵɵproperty (node_modules/@angular/core/fesm2022/core.mjs:21258:9)
            at templateFn (ng:///ChallengeDialogComponent.js:49:9)
            at executeTemplate (node_modules/@angular/core/fesm2022/core.mjs:11268:9)
            at refreshView (node_modules/@angular/core/fesm2022/core.mjs:12791:13)
            at detectChangesInView$1 (node_modules/@angular/core/fesm2022/core.mjs:13015:9)
            at detectChangesInViewIfAttached (node_modules/@angular/core/fesm2022/core.mjs:12978:5)
            at detectChangesInComponent (node_modules/@angular/core/fesm2022/core.mjs:12967:5)
Chrome Headless 124.0.6367.119 (Mac OS 10.15.7) LoginformComponent should create FAILED
        Error: NG0304: 'app-inputfield' is not a known element (used in the 'LoginformComponent' component template):
        1. If 'app-inputfield' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
        2. If 'app-inputfield' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        error properties: Object({ code: 304 })
            at validateElementIsKnown (node_modules/@angular/core/fesm2022/core.mjs:9662:23)
            at ɵɵelementStart (node_modules/@angular/core/fesm2022/core.mjs:22997:9)
            at ɵɵelement (node_modules/@angular/core/fesm2022/core.mjs:23072:5)
            at templateFn (ng:///LoginformComponent.js:14:9)
            at executeTemplate (node_modules/@angular/core/fesm2022/core.mjs:11268:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12470:13)
            at renderComponent (node_modules/@angular/core/fesm2022/core.mjs:12416:5)
            at renderChildComponents (node_modules/@angular/core/fesm2022/core.mjs:12518:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12498:13)
            at ComponentFactory.create (node_modules/@angular/core/fesm2022/core.mjs:15859:17)
Chrome Headless 124.0.6367.119 (Mac OS 10.15.7) RoadmapComponent should create FAILED
        Error: NG0304: 'app-challenge-button' is not a known element (used in the 'RoadmapComponent' component template):
        1. If 'app-challenge-button' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
        2. If 'app-challenge-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        error properties: Object({ code: 304 })
            at validateElementIsKnown (node_modules/@angular/core/fesm2022/core.mjs:9662:23)
            at ɵɵelementStart (node_modules/@angular/core/fesm2022/core.mjs:22997:9)
            at ɵɵelement (node_modules/@angular/core/fesm2022/core.mjs:23072:5)
            at templateFn (ng:///RoadmapComponent.js:6:5)
            at executeTemplate (node_modules/@angular/core/fesm2022/core.mjs:11268:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12470:13)
            at createAndRenderEmbeddedLView (node_modules/@angular/core/fesm2022/core.mjs:12540:9)
            at TemplateRef.createEmbeddedViewImpl (node_modules/@angular/core/fesm2022/core.mjs:13393:31)
            at ViewContainerRef.createEmbeddedView (node_modules/@angular/core/fesm2022/core.mjs:16191:37)
            at node_modules/@angular/common/fesm2022/common.mjs:3173:31
Chrome Headless 124.0.6367.119 (Mac OS 10.15.7) TimerComponent should create FAILED
        Error: NG0302: The pipe 'timer' could not be found in the 'TimerComponent' component. Verify that it is declared or imported in this module. Find more at https://angular.io/errors/NG0302
        error properties: Object({ code: -302 })
            at getPipeDef (node_modules/@angular/core/fesm2022/core.mjs:28280:15)
            at ɵɵpipe (node_modules/@angular/core/fesm2022/core.mjs:28221:19)
            at templateFn (ng:///TimerComponent.js:8:9)
            at executeTemplate (node_modules/@angular/core/fesm2022/core.mjs:11268:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12470:13)
            at renderComponent (node_modules/@angular/core/fesm2022/core.mjs:12416:5)
            at renderChildComponents (node_modules/@angular/core/fesm2022/core.mjs:12518:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12498:13)
            at ComponentFactory.create (node_modules/@angular/core/fesm2022/core.mjs:15859:17)
            at initComponent (node_modules/@angular/core/fesm2022/testing.mjs:1980:51)
Chrome Headless 124.0.6367.119 (Mac OS 10.15.7) AuthenticationpageComponent should create FAILED
        Error: NG0304: 'router-outlet' is not a known element (used in the 'AuthenticationpageComponent' component template):
        1. If 'router-outlet' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
        2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        error properties: Object({ code: 304 })
            at validateElementIsKnown (node_modules/@angular/core/fesm2022/core.mjs:9662:23)
            at ɵɵelementStart (node_modules/@angular/core/fesm2022/core.mjs:22997:9)
            at ɵɵelement (node_modules/@angular/core/fesm2022/core.mjs:23072:5)
            at templateFn (ng:///AuthenticationpageComponent.js:8:35)
            at executeTemplate (node_modules/@angular/core/fesm2022/core.mjs:11268:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12470:13)
            at renderComponent (node_modules/@angular/core/fesm2022/core.mjs:12416:5)
            at renderChildComponents (node_modules/@angular/core/fesm2022/core.mjs:12518:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12498:13)
            at ComponentFactory.create (node_modules/@angular/core/fesm2022/core.mjs:15859:17)
Chrome Headless 124.0.6367.119 (Mac OS 10.15.7) ChallengeButtonComponent should create FAILED
        Error: NG0304: 'app-challenge-dialog' is not a known element (used in the 'ChallengeButtonComponent' component template):
        1. If 'app-challenge-dialog' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
        2. If 'app-challenge-dialog' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        error properties: Object({ code: 304 })
            at validateElementIsKnown (node_modules/@angular/core/fesm2022/core.mjs:9662:23)
            at ɵɵelementStart (node_modules/@angular/core/fesm2022/core.mjs:22997:9)
            at templateFn (ng:///ChallengeButtonComponent.js:20:9)
            at executeTemplate (node_modules/@angular/core/fesm2022/core.mjs:11268:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12470:13)
            at renderComponent (node_modules/@angular/core/fesm2022/core.mjs:12416:5)
            at renderChildComponents (node_modules/@angular/core/fesm2022/core.mjs:12518:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12498:13)
            at ComponentFactory.create (node_modules/@angular/core/fesm2022/core.mjs:15859:17)
            at initComponent (node_modules/@angular/core/fesm2022/testing.mjs:1980:51)
Chrome Headless 124.0.6367.119 (Mac OS 10.15.7) MainpageComponent should create FAILED
        Error: NG0304: 'app-loader' is not a known element (used in the 'MainpageComponent' component template):
        1. If 'app-loader' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
        2. If 'app-loader' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        error properties: Object({ code: 304 })
            at validateElementIsKnown (node_modules/@angular/core/fesm2022/core.mjs:9662:23)
            at ɵɵelementStart (node_modules/@angular/core/fesm2022/core.mjs:22997:9)
            at ɵɵelement (node_modules/@angular/core/fesm2022/core.mjs:23072:5)
            at templateFn (ng:///MainpageComponent.js:8:9)
            at executeTemplate (node_modules/@angular/core/fesm2022/core.mjs:11268:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12470:13)
            at renderComponent (node_modules/@angular/core/fesm2022/core.mjs:12416:5)
            at renderChildComponents (node_modules/@angular/core/fesm2022/core.mjs:12518:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12498:13)
            at ComponentFactory.create (node_modules/@angular/core/fesm2022/core.mjs:15859:17)
Chrome Headless 124.0.6367.119 (Mac OS 10.15.7) StatisticHeaderComponent should create FAILED
        Error: NG0304: 'app-timer' is not a known element (used in the 'StatisticHeaderComponent' component template):
        1. If 'app-timer' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
        2. If 'app-timer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        error properties: Object({ code: 304 })
            at validateElementIsKnown (node_modules/@angular/core/fesm2022/core.mjs:9662:23)
            at ɵɵelementStart (node_modules/@angular/core/fesm2022/core.mjs:22997:9)
            at ɵɵelement (node_modules/@angular/core/fesm2022/core.mjs:23072:5)
            at templateFn (ng:///StatisticHeaderComponent.js:17:9)
            at executeTemplate (node_modules/@angular/core/fesm2022/core.mjs:11268:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12470:13)
            at renderComponent (node_modules/@angular/core/fesm2022/core.mjs:12416:5)
            at renderChildComponents (node_modules/@angular/core/fesm2022/core.mjs:12518:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12498:13)
            at ComponentFactory.create (node_modules/@angular/core/fesm2022/core.mjs:15859:17)
Chrome Headless 124.0.6367.119 (Mac OS 10.15.7) AppComponent should render title FAILED
        Error: NG0304: 'app-toast' is not a known element (used in the 'AppComponent' component template):
        1. If 'app-toast' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
        2. If 'app-toast' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        error properties: Object({ code: 304 })
            at validateElementIsKnown (node_modules/@angular/core/fesm2022/core.mjs:9662:23)
            at ɵɵelementStart (node_modules/@angular/core/fesm2022/core.mjs:22997:9)
            at ɵɵelement (node_modules/@angular/core/fesm2022/core.mjs:23072:5)
            at templateFn (ng:///AppComponent.js:5:57)
            at executeTemplate (node_modules/@angular/core/fesm2022/core.mjs:11268:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12470:13)
            at renderComponent (node_modules/@angular/core/fesm2022/core.mjs:12416:5)
            at renderChildComponents (node_modules/@angular/core/fesm2022/core.mjs:12518:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12498:13)
            at ComponentFactory.create (node_modules/@angular/core/fesm2022/core.mjs:15859:17)
Chrome Headless 124.0.6367.119 (Mac OS 10.15.7) AppComponent should create the app FAILED
        Error: NG0304: 'app-toast' is not a known element (used in the 'AppComponent' component template):
        1. If 'app-toast' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
        2. If 'app-toast' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        error properties: Object({ code: 304 })
            at validateElementIsKnown (node_modules/@angular/core/fesm2022/core.mjs:9662:23)
            at ɵɵelementStart (node_modules/@angular/core/fesm2022/core.mjs:22997:9)
            at ɵɵelement (node_modules/@angular/core/fesm2022/core.mjs:23072:5)
            at templateFn (ng:///AppComponent.js:5:57)
            at executeTemplate (node_modules/@angular/core/fesm2022/core.mjs:11268:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12470:13)
            at renderComponent (node_modules/@angular/core/fesm2022/core.mjs:12416:5)
            at renderChildComponents (node_modules/@angular/core/fesm2022/core.mjs:12518:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12498:13)
            at ComponentFactory.create (node_modules/@angular/core/fesm2022/core.mjs:15859:17)
Chrome Headless 124.0.6367.119 (Mac OS 10.15.7) AppComponent should have as title 'frontend' FAILED
        Error: NG0304: 'app-toast' is not a known element (used in the 'AppComponent' component template):
        1. If 'app-toast' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
        2. If 'app-toast' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        error properties: Object({ code: 304 })
            at validateElementIsKnown (node_modules/@angular/core/fesm2022/core.mjs:9662:23)
            at ɵɵelementStart (node_modules/@angular/core/fesm2022/core.mjs:22997:9)
            at ɵɵelement (node_modules/@angular/core/fesm2022/core.mjs:23072:5)
            at templateFn (ng:///AppComponent.js:5:57)
            at executeTemplate (node_modules/@angular/core/fesm2022/core.mjs:11268:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12470:13)
            at renderComponent (node_modules/@angular/core/fesm2022/core.mjs:12416:5)
            at renderChildComponents (node_modules/@angular/core/fesm2022/core.mjs:12518:9)
            at renderView (node_modules/@angular/core/fesm2022/core.mjs:12498:13)
            at ComponentFactory.create (node_modules/@angular/core/fesm2022/core.mjs:15859:17)
Chrome Headless 124.0.6367.119 (Mac OS 10.15.7): Executed 19 of 19 (12 FAILED) (0.113 secs / 0.092 secs)
TOTAL: 12 FAILED, 7 SUCCESS
Chrome Headless 124.0.6367.119 (Mac OS 10.15.7) ERROR
  Disconnected Client disconnected from CONNECTED state (transport close)
Chrome Headless 124.0.6367.119 (Mac OS 10.15.7): Executed 19 of 19 (12 FAILED) (0.113 secs / 0.092 secs)
Chrome Headless 124.0.6367.119 (Mac OS 10.15.7) ERROR
  Disconnected Client disconnected from CONNECTED state (transport close)
```

**Comment by Jstn2004** [comment]
Habe bei allem Komponenten die Fehler behoben, `ng test` sollte jetzt funktionieren
